# Generated by Django 4.0.1 on 2022-02-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_pet_activity_alter_pet_add_breed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='activity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
