# Generated by Django 4.0.1 on 2022-02-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_pet_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='add_breed',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
