# Generated by Django 4.0.1 on 2022-02-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_pet_dislike_alter_pet_meal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='allergies',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='help_required',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='prefer_food',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
