# Generated by Django 4.0.1 on 2022-02-10 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_pet_allergies_alter_pet_help_required_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Monday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m0', models.CharField(choices=[('w', 'walk'), ('p', 'play'), ('f', 'food'), ('s', 'sleep'), ('b', 'bath')], max_length=10)),
                ('m3', models.CharField(choices=[('w', 'walk'), ('p', 'play'), ('f', 'food'), ('s', 'sleep'), ('b', 'bath')], max_length=10)),
                ('m6', models.CharField(choices=[('w', 'walk'), ('p', 'play'), ('f', 'food'), ('s', 'sleep'), ('b', 'bath')], max_length=10)),
                ('m9', models.CharField(choices=[('w', 'walk'), ('p', 'play'), ('f', 'food'), ('s', 'sleep'), ('b', 'bath')], max_length=10)),
                ('m12', models.CharField(choices=[('w', 'walk'), ('p', 'play'), ('f', 'food'), ('s', 'sleep'), ('b', 'bath')], max_length=10)),
                ('m15', models.CharField(choices=[('w', 'walk'), ('p', 'play'), ('f', 'food'), ('s', 'sleep'), ('b', 'bath')], max_length=10)),
                ('m18', models.CharField(choices=[('w', 'walk'), ('p', 'play'), ('f', 'food'), ('s', 'sleep'), ('b', 'bath')], max_length=10)),
                ('m21', models.CharField(choices=[('w', 'walk'), ('p', 'play'), ('f', 'food'), ('s', 'sleep'), ('b', 'bath')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Saturday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Sunday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Thrusday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tuesday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Wednesday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.monday')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.pet')),
            ],
        ),
    ]
