# Generated by Django 4.0.1 on 2022-02-10 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_friday_monday_saturday_sunday_thrusday_tuesday_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m0', models.CharField(blank=True, choices=[('w', 'walk'), ('p', 'play'), ('f', 'food'), ('s', 'sleep'), ('b', 'bath')], max_length=10)),
                ('m3', models.CharField(blank=True, choices=[('w', 'walk'), ('p', 'play'), ('f', 'food'), ('s', 'sleep'), ('b', 'bath')], max_length=10)),
                ('m6', models.CharField(blank=True, choices=[('w', 'walk'), ('p', 'play'), ('f', 'food'), ('s', 'sleep'), ('b', 'bath')], max_length=10)),
                ('m9', models.CharField(blank=True, choices=[('w', 'walk'), ('p', 'play'), ('f', 'food'), ('s', 'sleep'), ('b', 'bath')], max_length=10)),
                ('m12', models.CharField(blank=True, choices=[('w', 'walk'), ('p', 'play'), ('f', 'food'), ('s', 'sleep'), ('b', 'bath')], max_length=10)),
                ('m15', models.CharField(blank=True, choices=[('w', 'walk'), ('p', 'play'), ('f', 'food'), ('s', 'sleep'), ('b', 'bath')], max_length=10)),
                ('m18', models.CharField(blank=True, choices=[('w', 'walk'), ('p', 'play'), ('f', 'food'), ('s', 'sleep'), ('b', 'bath')], max_length=10)),
                ('m21', models.CharField(blank=True, choices=[('w', 'walk'), ('p', 'play'), ('f', 'food'), ('s', 'sleep'), ('b', 'bath')], max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Friday',
        ),
        migrations.DeleteModel(
            name='Saturday',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='mon',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='pet',
        ),
        migrations.DeleteModel(
            name='Sunday',
        ),
        migrations.DeleteModel(
            name='Thrusday',
        ),
        migrations.DeleteModel(
            name='Tuesday',
        ),
        migrations.DeleteModel(
            name='Wednesday',
        ),
        migrations.DeleteModel(
            name='Monday',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.AddField(
            model_name='dayschedule',
            name='fri',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fri', to='base.timeschedule'),
        ),
        migrations.AddField(
            model_name='dayschedule',
            name='mon',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mon', to='base.timeschedule'),
        ),
        migrations.AddField(
            model_name='dayschedule',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.pet'),
        ),
        migrations.AddField(
            model_name='dayschedule',
            name='sat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sat', to='base.timeschedule'),
        ),
        migrations.AddField(
            model_name='dayschedule',
            name='sun',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sun', to='base.timeschedule'),
        ),
        migrations.AddField(
            model_name='dayschedule',
            name='thr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='thr', to='base.timeschedule'),
        ),
        migrations.AddField(
            model_name='dayschedule',
            name='tue',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tue', to='base.timeschedule'),
        ),
        migrations.AddField(
            model_name='dayschedule',
            name='wed',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wed', to='base.timeschedule'),
        ),
    ]
